spring:
  application:
    name: watchtower
  datasource:
    url: jdbc:postgresql://localhost:5432/watchtower
    username: watchtower_user
    password: watchtower_dev_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
